language: node_js # 언어는 node_js
node_js:
  - "12.8.0" # node_js에 버전 12.8.0
before_install: # 패키지를 다운로드 받기 전
  - npm install -g yarn # yarn을 글로벌로 설치
branches:
  only:
    - main
notifications: # 성공 실패 여부 알림
  email:
    recipients:
      - wkdaudwn11@naver.com
